exports.resources = {
	searchNotePlaceholder: "Wyszukaj notatki...",
	notePlaceholder: "Zanotujmy coś...",
	boldText: "pogrubienie",
	italicText: "kursywa",
	preformatedText: "formatowanie",	
	resetFilter: "Usuń filtrowanie",
	removeAllNotes: "Usuń wszystkie notatki",
	accountSettings: "Ustawienia konta",
	logOut: "Wyloguj się",
	aDayAgo: "dzień temu",
	daysAgo: "dni temu",
	anHourAgo: "godzinę temu",
	hoursAgo1: "godzin temu",
	hoursAgo2: "godziny temu",
	aMinuteAgo: "minutę temu",
	minutesAgo1: "minut temu",
	minutesAgo2: "minuty temu",
	justNow: "przed chwilą",
	halfAMinuteAgo: "pół minuty temu",
	almostAMinuteAgo: "prawie minutę temu"
}